### ISSUE TITLE
Collection student response data export

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#19]
In the Collection options, we require an option to export all the collection data in CSV format.

This data should look like this in the first instance:

![image](https://cloud.githubusercontent.com/assets/4758245/13243915/6a6a0a36-da56-11e5-881a-6362d9a412e6.png)

**Comment by nathansherburn** [comment]
I've pushed a version with this functionality however I'm guessing we'd like to collapse sessions in the case that they have the same _question text_, _answer options_ and _correct answers marked_.

**Comment by aj1331** [comment]
I didn't get time to finish the export collection dialog either. I'm going to reopen this and push it back to 0.5.2, which we can finish tomorrow.

**Comment by nathansherburn** [comment]
Collapsing multiple sessions into one has been added.

I'd like to neaten the code up a bit but the functionality is there and can be used for marking now.

**Comment by aj1331** [comment]
Reopened because the Export Results dialog still isn't working with collections.
